# Generated by Django 5.0.9 on 2026-05-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionists', '0003_alter_receptionistprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionistprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
