# Generated by Django 6.0.4 on 2026-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_medicaltest_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltest',
            name='test_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
