# Generated by Django 4.2.30 on 2026-04-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_medicaltest_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
