# Generated by Django 5.0.9 on 2026-05-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_consultation_id_alter_medicaltest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
