# Generated by Django 6.0.4 on 2026-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_reschedulerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedulerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
