# Generated by Django 6.0.4 on 2026-04-28 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_fee'),
        ('doctors', '0004_alter_doctorschedule_day_of_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'confirmed', 'checked_in'])), fields=('doctor', 'appointment_date', 'start_time'), name='unique_active_doctor_slot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'confirmed', 'checked_in'])), fields=('patient', 'appointment_date', 'start_time'), name='unique_active_patient_slot'),
        ),
    ]
