# Generated by Django 6.0.4 on 2026-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_id_alter_appointmentqueue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentqueue',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
