# Generated by Django 6.0.4 on 2026-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
