# Generated by Django 6.0.4 on 2026-04-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorschedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="doctorscheduleexception",
            name="is_day_off",
            field=models.BooleanField(default=False),
        ),
    ]
