# Generated by Django 6.0.4 on 2026-04-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorscheduleexception',
            name='reason',
        ),
    ]
