# Generated by Django 6.0.4 on 2026-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_doctorschedule_day_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorschedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ]
            ),
        ),
    ]
