# Generated by Django 6.0.4 on 2026-04-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day_of_week',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='doctorscheduleexception',
            name='is_day_off',
            field=models.BooleanField(default=True),
        ),
    ]
