# Generated by Django 6.0.4 on 2026-05-02 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctorprofile_buffer_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='buffer_time',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
