# Generated by Django 6.0.4 on 2026-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('appointment_requested', 'Appointment Requested'), ('profile_updated', 'Profile Updated'), ('consultation_ready', 'Consultation Ready')], max_length=40),
        ),
    ]
